name: epub_view_example
description: Example
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  epub_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  quiver: ^3.2.1

flutter:
  assets:
    - assets/
  uses-material-design: true
